name: CI

on:
  watch:
    types: [started]
  #push:
  #  branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.1.0
      
    - name: Cache Paket
      uses: actions/cache@v1.1.2
      env:
        cache-name: cache-paket
      with:
        path: packages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('paket.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          
    - name: Cache NPM
      uses: actions/cache@v1.1.2
      env:
        cache-name: cache-npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Node version
      run: node --version

    - name: .NET version
      run: dotnet --info

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Install NPM dependencies (master)
      run: npm install
    
    - name: Run Semantic Release (master)
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_USERNAME: release-bot
        GIT_AUTHOR_NAME: release-bot
        GIT_COMMITTER_NAME: release-bot
        GIT_EMAIL: informatie.vlaanderen@vlaanderen.be
        GIT_AUTHOR_EMAIL: informatie.vlaanderen@vlaanderen.be
        GIT_COMMITTER_EMAIL: informatie.vlaanderen@vlaanderen.be
        CONFLUENCE_USERNAME: david.cumps@vlaanderen.be
        CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
